run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .github

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - gosec

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true

  gofmt:
    simplify: true

  revive:
    confidence: 0.8
    rules:
      - name: unexported-return
        disabled: true
      - name: unused-parameter
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
